---
apiVersion: v1
kind: Service
metadata:
  name: dstrategies-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: dstrategies-frontend